/**
 * the cookbook - recipe data
 * ---------------------------
 * BUILT_IN_RECIPES ships with the app and never gets edited or saved,
 * it's the starting library. Anything a person adds through the "add
 * a recipe" form gets saved separately to localStorage and merged in
 * at render time, so updating this file later won't ever touch what
 * someone's personally added.
 *
 * era: "classic" for long-standing dishes, "trending" for newer or
 * internet-viral ones, just flavor text shown as a small badge.
 */

const BUILT_IN_CATEGORIES = ["appetizer", "main", "soup", "dessert", "drink"];

const BUILT_IN_RECIPES = [
  {
    id: "b-margherita",
    name: "Margherita Pizza",
    cuisine: "Italy",
    category: "main",
    era: "classic",
    time: "40 min",
    servings: 2,
    color: "#c9772f",
    ingredients: [
      "1 pizza dough ball (store-bought or homemade)",
      "1/2 cup crushed San Marzano tomatoes",
      "8 oz fresh mozzarella, torn",
      "fresh basil leaves",
      "2 tbsp olive oil",
      "salt to taste",
    ],
    steps: [
      "Preheat your oven as hot as it goes, ideally with a pizza stone or steel inside, for at least 45 minutes.",
      "Stretch the dough into a round, leaving a slightly thicker edge for the crust.",
      "Spread the crushed tomatoes thinly, leaving the border bare. Season with a little salt.",
      "Scatter the torn mozzarella over the top and drizzle with olive oil.",
      "Bake until the crust is blistered and the cheese is bubbling, 6 to 10 minutes depending on your oven.",
      "Top with fresh basil right after it comes out, the residual heat will wilt it perfectly.",
    ],
  },
  {
    id: "b-tiramisu",
    name: "Tiramisu",
    cuisine: "Italy",
    category: "dessert",
    era: "classic",
    time: "30 min + chilling",
    servings: 8,
    color: "#7a5c3e",
    ingredients: [
      "6 egg yolks",
      "3/4 cup sugar",
      "16 oz mascarpone",
      "1 1/2 cups strong espresso, cooled",
      "24 ladyfinger cookies",
      "cocoa powder, for dusting",
    ],
    steps: [
      "Whisk egg yolks and sugar over a double boiler until pale and thick, then cool slightly.",
      "Fold in the mascarpone until smooth.",
      "Quickly dip each ladyfinger in the espresso and layer half of them in a dish.",
      "Spread half the mascarpone mixture over the layer, then repeat with the remaining ladyfingers and mascarpone.",
      "Dust generously with cocoa powder and chill for at least 4 hours, overnight is better.",
    ],
  },
  {
    id: "b-padthai",
    name: "Pad Thai",
    cuisine: "Thailand",
    category: "main",
    era: "classic",
    time: "35 min",
    servings: 3,
    color: "#d9884a",
    ingredients: [
      "8 oz rice noodles",
      "2 tbsp tamarind paste",
      "2 tbsp fish sauce",
      "2 tbsp palm sugar (or brown sugar)",
      "2 eggs",
      "1 cup bean sprouts",
      "3 green onions, chopped",
      "crushed peanuts and lime, to serve",
    ],
    steps: [
      "Soak the rice noodles in warm water until pliable, then drain.",
      "Whisk tamarind paste, fish sauce, and sugar together into a sauce.",
      "Scramble the eggs in a hot wok, push to one side, then add the noodles and sauce.",
      "Toss everything together until the noodles are coated and heated through.",
      "Stir in the bean sprouts and green onions just until wilted.",
      "Serve topped with crushed peanuts and a wedge of lime.",
    ],
  },
  {
    id: "b-butterchicken",
    name: "Butter Chicken",
    cuisine: "India",
    category: "main",
    era: "classic",
    time: "50 min",
    servings: 4,
    color: "#c9542f",
    ingredients: [
      "1.5 lb boneless chicken thighs, cubed",
      "1 cup plain yogurt",
      "2 tbsp butter",
      "1 onion, chopped",
      "3 garlic cloves, minced",
      "1 tbsp garam masala",
      "1 can (14 oz) crushed tomatoes",
      "1/2 cup heavy cream",
    ],
    steps: [
      "Marinate the chicken in yogurt and half the garam masala for at least 30 minutes.",
      "Sear the marinated chicken in butter until browned, then set aside.",
      "In the same pot, cook the onion and garlic until soft, then add the remaining garam masala.",
      "Add the crushed tomatoes and simmer for 15 minutes, then blend until smooth if you want it silky.",
      "Return the chicken to the pot, stir in the cream, and simmer until the chicken is cooked through.",
    ],
  },
  {
    id: "b-chai",
    name: "Masala Chai",
    cuisine: "India",
    category: "drink",
    era: "classic",
    time: "15 min",
    servings: 2,
    color: "#a8672f",
    ingredients: [
      "2 cups water",
      "1 cup whole milk",
      "2 black tea bags (or 2 tsp loose black tea)",
      "1 cinnamon stick",
      "4 green cardamom pods, crushed",
      "1 inch ginger, sliced",
      "sugar or honey, to taste",
    ],
    steps: [
      "Combine the water, cinnamon, cardamom, and ginger in a pot and bring to a simmer for 5 minutes.",
      "Add the tea and simmer for 2 more minutes.",
      "Pour in the milk and bring back to a gentle simmer, don't let it boil over.",
      "Sweeten to taste, strain into cups, and serve hot.",
    ],
  },
  {
    id: "b-alpastor",
    name: "Tacos al Pastor",
    cuisine: "Mexico",
    category: "main",
    era: "classic",
    time: "1 hr + marinating",
    servings: 4,
    color: "#c9542f",
    ingredients: [
      "2 lb pork shoulder, thinly sliced",
      "3 dried guajillo chiles, soaked",
      "2 tbsp achiote paste",
      "1/4 cup pineapple juice",
      "3 garlic cloves",
      "corn tortillas",
      "diced onion, cilantro, and pineapple, to serve",
    ],
    steps: [
      "Blend the soaked chiles, achiote paste, pineapple juice, and garlic into a smooth marinade.",
      "Coat the pork in the marinade and refrigerate for at least 4 hours, ideally overnight.",
      "Cook the pork in a hot skillet or griddle until charred at the edges and cooked through.",
      "Warm the tortillas and pile the pork on top.",
      "Finish with diced onion, cilantro, and a little fresh pineapple.",
    ],
  },
  {
    id: "b-birria",
    name: "Birria Tacos",
    cuisine: "Mexico",
    category: "main",
    era: "trending",
    time: "3 hrs",
    servings: 6,
    color: "#a8321f",
    ingredients: [
      "3 lb beef chuck roast",
      "4 dried guajillo chiles",
      "2 dried ancho chiles",
      "1 onion, quartered",
      "4 garlic cloves",
      "2 bay leaves",
      "corn tortillas",
      "shredded cheese, for frying",
    ],
    steps: [
      "Toast the dried chiles briefly, then simmer them with the onion, garlic, and bay leaves until soft.",
      "Blend the softened chiles and aromatics with a little of their liquid into a smooth sauce.",
      "Combine the beef and chile sauce in a pot, cover with water, and simmer low for 2.5 to 3 hours until the meat shreds easily.",
      "Shred the beef and keep the flavorful broth (the consomé) for dipping.",
      "Dip tortillas in the fat skimmed from the top of the broth, fill with beef and cheese, and fry on a griddle until crisp.",
      "Serve alongside a cup of the hot consomé for dipping.",
    ],
  },
  {
    id: "b-tagine",
    name: "Chicken Tagine",
    cuisine: "Morocco",
    category: "main",
    era: "classic",
    time: "1.5 hrs",
    servings: 4,
    color: "#c9942f",
    ingredients: [
      "4 chicken thighs",
      "1 onion, sliced",
      "3 garlic cloves, minced",
      "1 tsp cumin",
      "1 tsp cinnamon",
      "1/2 tsp saffron threads",
      "1 cup dried apricots",
      "1/2 cup green olives",
    ],
    steps: [
      "Brown the chicken thighs in a tagine or heavy pot, then set aside.",
      "Cook the onion and garlic until soft, then stir in the spices.",
      "Return the chicken to the pot along with the apricots and enough water or stock to come halfway up the chicken.",
      "Cover and simmer gently for about an hour, until the chicken is tender.",
      "Stir in the olives in the last 10 minutes and serve with couscous or bread.",
    ],
  },
  {
    id: "b-pho",
    name: "Pho Bo",
    cuisine: "Vietnam",
    category: "soup",
    era: "classic",
    time: "3 hrs",
    servings: 4,
    color: "#7a4a2f",
    ingredients: [
      "3 lb beef bones",
      "1 onion, halved and charred",
      "3 inch ginger, halved and charred",
      "1 cinnamon stick",
      "2 star anise",
      "rice noodles",
      "thinly sliced raw beef",
      "bean sprouts, basil, and lime, to serve",
    ],
    steps: [
      "Simmer the beef bones with the charred onion and ginger for at least 3 hours, skimming occasionally.",
      "Toast the cinnamon and star anise, then add to the broth for the last 30 minutes.",
      "Strain the broth and season with fish sauce and a little sugar to taste.",
      "Cook the rice noodles and divide them into bowls.",
      "Top with the thinly sliced raw beef, then ladle the boiling broth over to cook it instantly.",
      "Serve with bean sprouts, basil, and lime on the side.",
    ],
  },
  {
    id: "b-kimchifriedrice",
    name: "Kimchi Fried Rice",
    cuisine: "Korea",
    category: "main",
    era: "classic",
    time: "20 min",
    servings: 2,
    color: "#c9432f",
    ingredients: [
      "2 cups cooked, cold rice",
      "1 cup chopped kimchi",
      "2 tbsp kimchi juice",
      "1 tbsp gochujang",
      "2 eggs",
      "2 green onions, chopped",
      "sesame oil",
    ],
    steps: [
      "Cook the kimchi in a hot pan with a little oil until slightly caramelized.",
      "Add the rice, kimchi juice, and gochujang, breaking up the rice as you stir-fry it.",
      "Push everything to one side and fry the eggs sunny side up in the same pan.",
      "Plate the rice, top with the fried eggs and green onions, and finish with a drizzle of sesame oil.",
    ],
  },
  {
    id: "b-dalgona",
    name: "Dalgona Coffee",
    cuisine: "Korea",
    category: "drink",
    era: "trending",
    time: "10 min",
    servings: 1,
    color: "#8a5c3e",
    ingredients: [
      "2 tbsp instant coffee",
      "2 tbsp sugar",
      "2 tbsp hot water",
      "1 cup milk, cold or warm",
      "ice, optional",
    ],
    steps: [
      "Combine the instant coffee, sugar, and hot water in a bowl.",
      "Whisk vigorously (or use a hand mixer) for several minutes until it turns pale, thick, and fluffy.",
      "Pour the milk into a glass over ice if you want it cold.",
      "Spoon the whipped coffee on top and stir together right before drinking.",
    ],
  },
  {
    id: "b-hummus",
    name: "Hummus",
    cuisine: "Lebanon",
    category: "appetizer",
    era: "classic",
    time: "15 min",
    servings: 6,
    color: "#c9a441",
    ingredients: [
      "1 can (15 oz) chickpeas, drained",
      "1/4 cup tahini",
      "2 tbsp lemon juice",
      "1 garlic clove",
      "2 tbsp olive oil, plus more to serve",
      "1/4 tsp cumin",
      "cold water as needed",
    ],
    steps: [
      "Blend the chickpeas, tahini, lemon juice, garlic, olive oil, and cumin until mostly smooth.",
      "Add cold water a tablespoon at a time while blending until it reaches a light, creamy texture.",
      "Taste and adjust salt and lemon as needed.",
      "Spread onto a plate, swirl the top, and finish with a drizzle of olive oil.",
    ],
  },
  {
    id: "b-baklava",
    name: "Baklava",
    cuisine: "Turkey",
    category: "dessert",
    era: "classic",
    time: "1.5 hrs",
    servings: 12,
    color: "#c9942f",
    ingredients: [
      "1 lb phyllo dough, thawed",
      "2 cups chopped walnuts or pistachios",
      "1 tsp cinnamon",
      "1 cup butter, melted",
      "1 cup sugar",
      "1 cup water",
      "1/4 cup honey",
      "1 tsp lemon juice",
    ],
    steps: [
      "Mix the chopped nuts with cinnamon.",
      "Layer sheets of phyllo in a buttered baking dish, brushing each sheet with melted butter, building up about 8 layers.",
      "Spread a layer of the nut mixture, then continue layering buttered phyllo and nuts until everything is used, finishing with phyllo on top.",
      "Cut into diamond shapes before baking, then bake at 350°F (175°C) until golden, about 45 minutes.",
      "Meanwhile, simmer sugar, water, honey, and lemon juice into a syrup.",
      "Pour the warm syrup over the baklava as soon as it comes out of the oven, and let it soak in before serving.",
    ],
  },
  {
    id: "b-paella",
    name: "Paella",
    cuisine: "Spain",
    category: "main",
    era: "classic",
    time: "1 hr",
    servings: 6,
    color: "#c9772f",
    ingredients: [
      "2 cups bomba or short-grain rice",
      "4 cups chicken or seafood stock",
      "1/2 tsp saffron threads",
      "1 lb mixed shrimp and mussels",
      "1 chicken thigh, cubed",
      "1 red bell pepper, sliced",
      "3 garlic cloves, minced",
      "1 tomato, grated",
    ],
    steps: [
      "Steep the saffron in a little warm stock while you prepare everything else.",
      "Brown the chicken in a paella pan, then set aside.",
      "Cook the bell pepper and garlic, then stir in the grated tomato and cook until jammy.",
      "Add the rice and toast briefly, then pour in the stock and saffron.",
      "Simmer without stirring, nestling the chicken back in and adding the shrimp and mussels in the last 10 minutes.",
      "Let it rest a few minutes off heat, ideally with a crisp layer forming on the bottom, before serving.",
    ],
  },
  {
    id: "b-ceviche",
    name: "Ceviche",
    cuisine: "Peru",
    category: "appetizer",
    era: "classic",
    time: "25 min",
    servings: 4,
    color: "#4a8a6f",
    ingredients: [
      "1 lb firm white fish, cubed",
      "1 cup fresh lime juice",
      "1/2 red onion, thinly sliced",
      "1 aji amarillo or jalapeño, minced",
      "cilantro, chopped",
      "salt to taste",
      "sweet potato and corn, to serve",
    ],
    steps: [
      "Combine the fish with the lime juice and a pinch of salt, making sure it's fully covered.",
      "Let it marinate for 10 to 15 minutes, until the fish turns opaque, this is the acid \"cooking\" it.",
      "Stir in the red onion, chile, and cilantro just before serving.",
      "Serve immediately alongside boiled sweet potato and corn.",
    ],
  },
  {
    id: "b-dorowat",
    name: "Doro Wat",
    cuisine: "Ethiopia",
    category: "main",
    era: "classic",
    time: "1.5 hrs",
    servings: 4,
    color: "#a8321f",
    ingredients: [
      "4 chicken drumsticks and thighs",
      "2 large onions, finely chopped",
      "3 tbsp berbere spice blend",
      "3 tbsp butter (or niter kibbeh)",
      "3 garlic cloves, minced",
      "1 inch ginger, minced",
      "4 hard-boiled eggs",
    ],
    steps: [
      "Cook the chopped onions low and slow with no oil until deeply softened, this takes real patience, don't rush it.",
      "Add the butter, garlic, ginger, and berbere, and cook until fragrant.",
      "Add the chicken and enough water to come partway up, then simmer covered until the chicken is tender.",
      "Nestle the hard-boiled eggs into the sauce for the last 10 minutes to warm through.",
      "Serve with injera bread to scoop everything up.",
    ],
  },
  {
    id: "b-jerk",
    name: "Jerk Chicken",
    cuisine: "Jamaica",
    category: "main",
    era: "classic",
    time: "45 min + marinating",
    servings: 4,
    color: "#a8542f",
    ingredients: [
      "4 chicken thighs and drumsticks",
      "4 scotch bonnet peppers (or habanero)",
      "6 green onions",
      "3 garlic cloves",
      "2 tbsp allspice",
      "1 tbsp thyme",
      "1/4 cup soy sauce",
      "2 tbsp brown sugar",
    ],
    steps: [
      "Blend the peppers, green onions, garlic, allspice, thyme, soy sauce, and brown sugar into a marinade.",
      "Coat the chicken thoroughly and marinate for at least 4 hours, overnight is better.",
      "Grill over medium heat, turning occasionally, until charred and cooked through, about 35 to 40 minutes.",
      "Let it rest a few minutes before serving.",
    ],
  },
  {
    id: "b-smashburger",
    name: "Classic Smash Burger",
    cuisine: "USA",
    category: "main",
    era: "trending",
    time: "20 min",
    servings: 2,
    color: "#a8542f",
    ingredients: [
      "1/2 lb ground beef, 80/20",
      "2 slices American cheese",
      "2 burger buns",
      "1 tbsp diced onion",
      "salt and pepper",
      "burger sauce or ketchup and mustard",
    ],
    steps: [
      "Divide the beef into loose balls, don't compact them.",
      "Get a skillet screaming hot, place the balls down, top with diced onion, and smash flat immediately with a spatula.",
      "Season with salt and pepper, sear undisturbed until deeply browned, about 2 minutes.",
      "Flip, add cheese right away so it melts, and cook another minute.",
      "Toast the buns in the same pan, then build your burger with sauce of choice.",
    ],
  },
  {
    id: "b-bakedfeta",
    name: "Baked Feta Pasta",
    cuisine: "Finland (viral)",
    category: "main",
    era: "trending",
    time: "35 min",
    servings: 4,
    color: "#c9542f",
    ingredients: [
      "1 block (8 oz) feta cheese",
      "2 cups cherry tomatoes",
      "1/4 cup olive oil",
      "3 garlic cloves, sliced",
      "1 tsp chili flakes",
      "1 lb pasta of your choice",
      "fresh basil, torn",
    ],
    steps: [
      "Place the feta block in the center of a baking dish, surround with cherry tomatoes, and drizzle everything with olive oil.",
      "Scatter the garlic and chili flakes over the top and bake at 400°F (200°C) for 25 to 30 minutes, until the tomatoes burst and the feta is soft and golden.",
      "Meanwhile, cook the pasta and reserve a cup of the pasta water.",
      "Mash the baked feta and tomatoes together right in the dish, loosening with a splash of pasta water.",
      "Toss with the pasta and finish with fresh basil.",
    ],
  },
  {
    id: "b-cookies",
    name: "Chocolate Chip Cookies",
    cuisine: "USA",
    category: "dessert",
    era: "classic",
    time: "30 min",
    servings: 18,
    color: "#8a5c3e",
    ingredients: [
      "2 1/4 cups flour",
      "1 tsp baking soda",
      "1 cup butter, softened",
      "3/4 cup brown sugar",
      "3/4 cup white sugar",
      "2 eggs",
      "2 cups chocolate chips",
    ],
    steps: [
      "Cream the butter with both sugars until light and fluffy.",
      "Beat in the eggs one at a time.",
      "Mix in the flour and baking soda just until combined, then fold in the chocolate chips.",
      "Scoop onto a baking sheet and bake at 375°F (190°C) for 9 to 11 minutes, until the edges are golden but the centers still look slightly underdone.",
      "Let them sit on the sheet a couple minutes before moving, they'll firm up as they cool.",
    ],
  },
  {
    id: "b-kungpao",
    name: "Kung Pao Chicken",
    cuisine: "China",
    category: "main",
    era: "classic",
    time: "30 min",
    servings: 3,
    color: "#a8321f",
    ingredients: [
      "1 lb chicken thighs, cubed",
      "1/3 cup roasted peanuts",
      "6 dried red chiles",
      "3 garlic cloves, sliced",
      "1 inch ginger, sliced",
      "2 tbsp soy sauce",
      "1 tbsp black vinegar",
      "1 tsp sugar",
    ],
    steps: [
      "Stir-fry the dried chiles in hot oil briefly until fragrant, careful not to burn them.",
      "Add the chicken and cook until mostly done.",
      "Add the garlic and ginger and stir-fry another minute.",
      "Combine the soy sauce, vinegar, and sugar, pour it in, and toss to coat.",
      "Stir in the peanuts at the very end so they stay crunchy.",
    ],
  },
  {
    id: "b-misoramen",
    name: "Miso Ramen",
    cuisine: "Japan",
    category: "soup",
    era: "classic",
    time: "40 min",
    servings: 2,
    color: "#7a5c3e",
    ingredients: [
      "4 cups chicken or pork stock",
      "3 tbsp miso paste",
      "1 tbsp soy sauce",
      "1 tsp sesame oil",
      "2 portions ramen noodles",
      "soft-boiled eggs, corn, and green onion, to serve",
    ],
    steps: [
      "Whisk the miso paste into a little warm stock until smooth, then combine with the rest of the stock.",
      "Simmer gently with the soy sauce and sesame oil, don't let it boil hard once the miso is in.",
      "Cook the ramen noodles separately according to the package.",
      "Divide the noodles into bowls, ladle the hot broth over, and top with soft-boiled eggs, corn, and green onion.",
    ],
  },
];
