/**
 * soup-of-the-day recipes
 * -----------------------
 * Each recipe is real and cookable, not a placeholder. Add your own by
 * copying the shape below. `moods` controls which mood buttons will
 * surface this recipe, a recipe can belong to more than one mood.
 */

const RECIPES = [
  {
    name: "classic tomato basil",
    moods: ["cozy", "comfort"],
    time: "35 min",
    servings: 4,
    color: "#d9714e",
    ingredients: [
      "2 tbsp olive oil",
      "1 onion, chopped",
      "3 garlic cloves, minced",
      "2 cans (28 oz each) whole peeled tomatoes",
      "1 cup vegetable or chicken stock",
      "1/2 cup fresh basil, torn",
      "1/2 cup heavy cream (optional)",
      "salt and pepper to taste",
    ],
    steps: [
      "Warm the olive oil in a large pot over medium heat. Add the onion and cook until soft, about 6 minutes.",
      "Add the garlic and cook 1 more minute, until fragrant.",
      "Pour in the tomatoes (crushing them with your hands or a spoon as they go in) and the stock. Simmer for 20 minutes.",
      "Blend until smooth, using an immersion blender or in batches in a regular blender.",
      "Stir in the basil and cream if using. Season with salt and pepper, then serve hot.",
    ],
  },
  {
    name: "grandma-style chicken noodle",
    moods: ["comfort", "cozy"],
    time: "50 min",
    servings: 6,
    color: "#d9a441",
    ingredients: [
      "1 tbsp butter",
      "1 onion, chopped",
      "2 carrots, sliced",
      "2 celery stalks, sliced",
      "8 cups chicken stock",
      "2 cups cooked, shredded chicken",
      "2 cups egg noodles",
      "2 sprigs fresh thyme",
      "salt and pepper to taste",
    ],
    steps: [
      "Melt the butter in a large pot over medium heat. Add the onion, carrots, and celery, and cook until softened, about 8 minutes.",
      "Pour in the stock and thyme, and bring to a gentle boil.",
      "Add the noodles and cook according to package directions, usually 7 to 9 minutes.",
      "Stir in the shredded chicken and cook just until warmed through.",
      "Season with salt and pepper, remove the thyme sprigs, and serve.",
    ],
  },
  {
    name: "miso soup",
    moods: ["quick", "light"],
    time: "15 min",
    servings: 2,
    color: "#7a8c6b",
    ingredients: [
      "4 cups dashi stock (or water with 1 tsp dashi powder)",
      "3 tbsp miso paste",
      "1/2 block soft tofu, cubed",
      "2 green onions, sliced",
      "a small handful of dried wakame seaweed",
    ],
    steps: [
      "Bring the dashi stock to a gentle simmer, don't let it boil hard.",
      "Ladle a bit of the hot stock into a small bowl, whisk in the miso paste until smooth, then stir it back into the pot.",
      "Add the tofu and wakame, and warm through for about 2 minutes.",
      "Ladle into bowls and top with the green onions.",
    ],
  },
  {
    name: "red lentil soup",
    moods: ["comfort", "quick"],
    time: "30 min",
    servings: 4,
    color: "#b5541e",
    ingredients: [
      "1 tbsp olive oil",
      "1 onion, chopped",
      "2 garlic cloves, minced",
      "1 tsp cumin",
      "1 tsp turmeric",
      "1 cup red lentils, rinsed",
      "4 cups vegetable stock",
      "juice of half a lemon",
      "salt to taste",
    ],
    steps: [
      "Heat the oil in a pot over medium heat. Cook the onion until soft, about 5 minutes.",
      "Add the garlic, cumin, and turmeric, and stir for 1 minute until fragrant.",
      "Add the lentils and stock. Bring to a boil, then reduce heat and simmer for 18 to 20 minutes, until the lentils are soft.",
      "Blend partially or fully, depending on the texture you like.",
      "Stir in the lemon juice, season with salt, and serve.",
    ],
  },
  {
    name: "potato leek soup",
    moods: ["cozy", "comfort"],
    time: "40 min",
    servings: 4,
    color: "#c9a86a",
    ingredients: [
      "2 tbsp butter",
      "2 leeks, white and light green parts, sliced and rinsed well",
      "4 cups potatoes, peeled and cubed",
      "4 cups chicken or vegetable stock",
      "1/2 cup cream or whole milk",
      "salt and pepper to taste",
      "chives, for topping",
    ],
    steps: [
      "Melt the butter in a pot over medium heat. Add the leeks and cook until soft, about 8 minutes.",
      "Add the potatoes and stock. Bring to a boil, then simmer for 20 minutes, until the potatoes are fork-tender.",
      "Blend until smooth (or leave it chunky, if you prefer it rustic).",
      "Stir in the cream, season with salt and pepper, and top with chives before serving.",
    ],
  },
  {
    name: "hearty minestrone",
    moods: ["cozy", "comfort"],
    time: "45 min",
    servings: 6,
    color: "#5e7a4f",
    ingredients: [
      "2 tbsp olive oil",
      "1 onion, chopped",
      "2 carrots, diced",
      "2 celery stalks, diced",
      "3 garlic cloves, minced",
      "1 can (14 oz) diced tomatoes",
      "6 cups vegetable stock",
      "1 can (15 oz) kidney beans, drained",
      "1 cup small pasta, like ditalini",
      "2 cups chopped kale or spinach",
      "parmesan, to serve",
    ],
    steps: [
      "Heat the oil in a large pot. Cook the onion, carrots, and celery until softened, about 8 minutes.",
      "Add the garlic and cook for 1 more minute.",
      "Add the tomatoes and stock, bring to a boil, then simmer for 15 minutes.",
      "Add the beans and pasta, and cook until the pasta is tender, about 10 minutes.",
      "Stir in the greens just until wilted, then serve topped with parmesan.",
    ],
  },
  {
    name: "roasted butternut squash soup",
    moods: ["cozy", "light"],
    time: "55 min",
    servings: 4,
    color: "#e2933a",
    ingredients: [
      "1 butternut squash, peeled and cubed",
      "1 onion, quartered",
      "3 tbsp olive oil",
      "4 cups vegetable stock",
      "1/2 tsp nutmeg",
      "1/2 cup coconut milk or cream",
      "salt and pepper to taste",
    ],
    steps: [
      "Preheat the oven to 400°F (200°C). Toss the squash and onion with the olive oil, then roast for 30 minutes, until soft and caramelized at the edges.",
      "Transfer the roasted vegetables to a pot with the stock and nutmeg. Simmer for 10 minutes.",
      "Blend until completely smooth.",
      "Stir in the coconut milk, season with salt and pepper, and serve.",
    ],
  },
  {
    name: "spicy black bean soup",
    moods: ["adventurous", "comfort"],
    time: "35 min",
    servings: 4,
    color: "#7a3b2e",
    ingredients: [
      "1 tbsp olive oil",
      "1 onion, chopped",
      "1 red bell pepper, diced",
      "2 garlic cloves, minced",
      "1 tbsp chili powder",
      "1 tsp smoked paprika",
      "3 cans (15 oz each) black beans, drained and rinsed",
      "4 cups vegetable stock",
      "juice of 1 lime",
      "cilantro and sour cream, to serve",
    ],
    steps: [
      "Heat the oil in a pot over medium heat. Cook the onion and bell pepper until soft, about 7 minutes.",
      "Add the garlic, chili powder, and smoked paprika, and stir for 1 minute.",
      "Add the beans and stock, bring to a boil, then simmer for 15 minutes.",
      "Blend about half the soup for a creamier texture, leaving the rest chunky.",
      "Stir in the lime juice, and serve topped with cilantro and sour cream.",
    ],
  },
  {
    name: "thai coconut curry soup",
    moods: ["adventurous", "light"],
    time: "30 min",
    servings: 4,
    color: "#c95b7a",
    ingredients: [
      "1 tbsp coconut oil",
      "2 tbsp red curry paste",
      "1 can (14 oz) coconut milk",
      "3 cups vegetable or chicken stock",
      "1 cup mushrooms, sliced",
      "1 cup cooked shredded chicken or tofu",
      "juice of 1 lime",
      "1 tbsp fish sauce or soy sauce",
      "cilantro and chili, to serve",
    ],
    steps: [
      "Heat the coconut oil in a pot over medium heat. Add the curry paste and cook for 1 minute, until fragrant.",
      "Pour in the coconut milk and stock, and bring to a gentle simmer.",
      "Add the mushrooms and chicken or tofu, and simmer for 10 minutes.",
      "Stir in the lime juice and fish sauce.",
      "Serve topped with cilantro and fresh chili.",
    ],
  },
];
